FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release

WORKDIR /solution
# Copy the Directory.Build.props, Package.props and the editorconfig from the solution root
COPY ["Directory.Build.props", "."]
COPY ["Directory.Packages.props", "."]
COPY [".editorconfig", "."]

WORKDIR /solution/src
# Copy the Directory.Build.props from the /src directory into /solution/src
COPY ["src/Directory.Build.props", "."]

# Copy the project from /src
COPY ["src/Traditional.Api/Traditional.Api.csproj", "Traditional.Api/"]

WORKDIR /solution/src/Traditional.Api
# Restore the solution
RUN dotnet restore "Traditional.Api.csproj"

# Copy the rest of the files
COPY ["src/Traditional.Api", "."]

# Build the project
RUN dotnet build "Traditional.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Traditional.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Traditional.Api.dll"]
