### Get the top level categories

@rootCategoryId = 1
@articleNumber = 1

GET {{host}}/categories/children?rootCategoryId={{rootCategoryId}}&articleNumber={{articleNumber}}
Content-Type: application/json
Accept: application/json

### Get children of a category

@CategoryNumber = 1

GET {{host}}/categories/children?rootCategoryId={{rootCategoryId}}&articleNumber={{articleNumber}}&categoryNumber={{CategoryNumber}}
Content-Type: application/json
Accept: application/json

### Example response

# [
#     {
#         "categoryNumber": 1,
#         "label": "Category Name 1",
#         "isSelected": true,
#         "isLeaf": false
#     },
#     {
#         "categoryNumber": 2,
#         "label": "Category Name 2",
#         "isSelected": false,
#         "isLeaf": false
#     }
# ]
