### Get attributes by rootCategoryId and article number

@rootCategoryId = 1
@articleNumber = 1

GET {{host}}/attributes?rootCategoryId={{rootCategoryId}}&articleNumber={{articleNumber}}
Content-Type: application/json

### Expected response

# [
#   {
#     "attributeId": 1,
#     "attributeName": "Attribute Name 1",
#     "type": "BOOLEAN",
#     "maxValues": 1,
#     "maxLength": null,
#     "minLength": null,
#     "description": null,
#     "allowedValues": [],
#     "exampleValues": [],
#     "canAddAllowedValues": false,
#     "subAttributes": [
#       "301"
#     ],
#     "attributePath": [],
#     "isEditable": true,
#     "values": [
#       {
#         "characteristicId": 0,
#         "values": []
#       },
#       {
#         "characteristicId": 1,
#         "values": []
#       },
#       {
#       "characteristicId": 2,
#       "values": []
#       }
#     ],
#     "minValues": 1,
#     "dependentAttributes": []
#   }
# ]
