### Update attribute values for an article

@rootCategoryId = 1
@articleNumber = 1

PUT {{host}}/attributes
Content-Type: application/json

{
    "rootCategoryId": {{rootCategoryId}},
    "articleNumber": "{{articleNumber}}",
    "newAttributeValues": [
        {
            "attributeId": 1,
            "innerValues": [
                {
                    "characteristicId": 0,
                    "values": ["true"]
                }
            ]
        },
        {
            "attributeId": 30001,
            "innerValues": [
                {
                    "characteristicId": 0,
                    "values": ["true"]
                }
            ]
        },
        {
            "attributeId": 60001,
            "innerValues": [
                {
                    "characteristicId": 0,
                    "values": ["true"]
                }
            ]
        }
    ]
}

### Expected response

# No content
