@host = http://localhost:5012

@rootCategoryId = 1
@articleNumber = 1

### Search categories (rootCategoryId, articleNumber, CategoryNumber)

@CategoryNumber = 2

GET {{host}}/categories/search?rootCategoryId={{rootCategoryId}}&articleNumber={{articleNumber}}&categoryNumber={{CategoryNumber}}
Accept: application/json

### Search categories (rootCategoryId, articleNumber, searchTerm)

@searchTerm = Category Name 222

GET {{host}}/categories/search?rootCategoryId={{rootCategoryId}}&articleNumber={{articleNumber}}&searchTerm={{searchTerm}}
Accept: application/json

### Example response

# [
#   {
#     "categoryNumber": 220,
#     "label": "Category Name 220",
#     "isSelected": false,
#     "isLeaf": false,
#     "children": [
#       {
#         "categoryNumber": 221,
#         "label": "Category Name 221",
#         "isSelected": false,
#         "isLeaf": true,
#         "children": [
#           {
#             "categoryNumber": 222,
#             "label": "Category Name 222",
#             "isSelected": false,
#             "isLeaf": true,
#             "children": []
#           }
#         ]
#       }
#     ]
#   }
# ]
